//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.CrudXMLServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerData", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
    [System.SerializableAttribute()]
    public partial class CustomerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable CustomersTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable CustomersTable {
            get {
                return this.CustomersTableField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersTableField, value) != true)) {
                    this.CustomersTableField = value;
                    this.RaisePropertyChanged("CustomersTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrudXMLServiceReference.ICrudXMLService")]
    public interface ICrudXMLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudXMLService/InsertUserDetails", ReplyAction="http://tempuri.org/ICrudXMLService/InsertUserDetailsResponse")]
        void InsertUserDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudXMLService/InsertUserDetails", ReplyAction="http://tempuri.org/ICrudXMLService/InsertUserDetailsResponse")]
        System.Threading.Tasks.Task InsertUserDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudXMLService/GetUserDetails", ReplyAction="http://tempuri.org/ICrudXMLService/GetUserDetailsResponse")]
        WindowsFormsApp.CrudXMLServiceReference.CustomerData GetUserDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudXMLService/GetUserDetails", ReplyAction="http://tempuri.org/ICrudXMLService/GetUserDetailsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp.CrudXMLServiceReference.CustomerData> GetUserDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudXMLService/UpdateCustomer", ReplyAction="http://tempuri.org/ICrudXMLService/UpdateCustomerResponse")]
        void UpdateCustomer(int customerId, string name, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudXMLService/UpdateCustomer", ReplyAction="http://tempuri.org/ICrudXMLService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task UpdateCustomerAsync(int customerId, string name, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudXMLService/DeleteCustomer", ReplyAction="http://tempuri.org/ICrudXMLService/DeleteCustomerResponse")]
        void DeleteCustomer(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudXMLService/DeleteCustomer", ReplyAction="http://tempuri.org/ICrudXMLService/DeleteCustomerResponse")]
        System.Threading.Tasks.Task DeleteCustomerAsync(int customerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrudXMLServiceChannel : WindowsFormsApp.CrudXMLServiceReference.ICrudXMLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrudXMLServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp.CrudXMLServiceReference.ICrudXMLService>, WindowsFormsApp.CrudXMLServiceReference.ICrudXMLService {
        
        public CrudXMLServiceClient() {
        }
        
        public CrudXMLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrudXMLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudXMLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudXMLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertUserDetails() {
            base.Channel.InsertUserDetails();
        }
        
        public System.Threading.Tasks.Task InsertUserDetailsAsync() {
            return base.Channel.InsertUserDetailsAsync();
        }
        
        public WindowsFormsApp.CrudXMLServiceReference.CustomerData GetUserDetails() {
            return base.Channel.GetUserDetails();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp.CrudXMLServiceReference.CustomerData> GetUserDetailsAsync() {
            return base.Channel.GetUserDetailsAsync();
        }
        
        public void UpdateCustomer(int customerId, string name, string country) {
            base.Channel.UpdateCustomer(customerId, name, country);
        }
        
        public System.Threading.Tasks.Task UpdateCustomerAsync(int customerId, string name, string country) {
            return base.Channel.UpdateCustomerAsync(customerId, name, country);
        }
        
        public void DeleteCustomer(int customerId) {
            base.Channel.DeleteCustomer(customerId);
        }
        
        public System.Threading.Tasks.Task DeleteCustomerAsync(int customerId) {
            return base.Channel.DeleteCustomerAsync(customerId);
        }
    }
}
