//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.CrudXMLServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrudXMLServiceReference.ICrudXMLService")]
    public interface ICrudXMLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudXMLService/InsertUserDetails", ReplyAction="http://tempuri.org/ICrudXMLService/InsertUserDetailsResponse")]
        void InsertUserDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudXMLService/InsertUserDetails", ReplyAction="http://tempuri.org/ICrudXMLService/InsertUserDetailsResponse")]
        System.Threading.Tasks.Task InsertUserDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrudXMLServiceChannel : WindowsFormsApp.CrudXMLServiceReference.ICrudXMLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrudXMLServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp.CrudXMLServiceReference.ICrudXMLService>, WindowsFormsApp.CrudXMLServiceReference.ICrudXMLService {
        
        public CrudXMLServiceClient() {
        }
        
        public CrudXMLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrudXMLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudXMLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudXMLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertUserDetails() {
            base.Channel.InsertUserDetails();
        }
        
        public System.Threading.Tasks.Task InsertUserDetailsAsync() {
            return base.Channel.InsertUserDetailsAsync();
        }
    }
}
